apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  clusterIP: None
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - protocol: TCP
    port: 3306 #service port
    targetPort: 3306 

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - protocol: TCP
    port: 3306 #service port
    targetPort: 3306 